message(STATUS "Searching for tests.")
list(APPEND CMAKE_MESSAGE_INDENT "  ")

# get all test directories. structure is Test_<DirectoryName>_<TestName>
file(GLOB CGE_TEST_DIRS LIST_DIRECTORIES true *)

foreach (dir IN LISTS CGE_TEST_DIRS)
    if (NOT IS_DIRECTORY ${dir}) #ignore CMakeLists.txt file
        CONTINUE()
    endif ()
    get_filename_component(dirname ${dir} NAME_WE)
    file(GLOB_RECURSE CGE_TESTS CONFIGURE_DEPENDS ${dir}/*.cpp) # find all tests
    # find all header files. header files are not tests, and instead are used as an optional testing framework.
    file(GLOB_RECURSE CGE_TESTS_FRAMEWORK CONFIGURE_DEPENDS ${dir}/*.h)
    foreach (file IN LISTS CGE_TESTS)
        get_filename_component(filename ${file} NAME_WE)
        set(testname "Test_${dirname}_${filename}")
        message(STATUS "${testname}: ${file}")
        add_executable(${testname} ${file} ${CGE_TESTS_FRAMEWORK})
        target_link_libraries(${testname} Crimson)
        cge_setup_content(${testname} "Content" "${CMAKE_CURRENT_SOURCE_DIR}/CommonContent")
        add_custom_command(
                TARGET ${testname} POST_BUILD
                COMMAND "${CMAKE_COMMAND}" -E copy_directory "${CMAKE_CURRENT_SOURCE_DIR}/CommonContent" "${CMAKE_CURRENT_BINARY_DIR}/Content"
                VERBATIM
        )
    endforeach ()
endforeach ()

list(POP_BACK CMAKE_MESSAGE_INDENT)